/** Severity levels for agent findings */
export type Severity = 'Critical' | 'High' | 'Medium' | 'Low';

/** Impact categories for scalability issues */
export type Impact = 'Performance' | 'Reliability' | 'Scalability' | 'Observability';

/** A single security issue found by Agent 1 */
export interface SecurityIssue {
  principle: string;
  severity: Severity;
  line: number;
  description: string;
  fix: string;
}

/** A single scalability issue found by Agent 2 */
export interface ScalabilityIssue {
  principle: string;
  impact: Impact;
  severity: Severity;
  line: number;
  description: string;
  fix: string;
}

/** Output from the Security Agent */
export interface SecurityReport {
  agent: 'security';
  file: string;
  issues: SecurityIssue[];
  passed: boolean;
}

/** Output from the Scalability Agent */
export interface ScalabilityReport {
  agent: 'scalability';
  file: string;
  issues: ScalabilityIssue[];
  passed: boolean;
}

/** Severity breakdown counts */
export interface SeverityBreakdown {
  passed: boolean;
  critical: number;
  high: number;
  medium: number;
  low: number;
}

/** Unified report generated by the orchestrator */
export interface UnifiedReport {
  file: string;
  timestamp: string;
  security: SeverityBreakdown;
  scalability: SeverityBreakdown;
  decision: string;
  retries: number;
}

/** File event from the watcher */
export interface FileEvent {
  filePath: string;
  content: string;
  triggerType: 'new file' | 'modified';
  timestamp: string;
}

/** Configuration loaded from environment */
export interface AgentConfig {
  watchPath: string;
  maxRetries: number;
  debounceMs: number;
  blockSeverities: Severity[];
  healthPort: number;
  reportsDir: string;
  reviewLog: string;
  logLevel: string;
}

/** Self-correction prompt context */
export interface CorrectionContext {
  securityIssues: SecurityIssue[];
  scalabilityIssues: ScalabilityIssue[];
  attempt: number;
  maxAttempts: number;
}
